echo "OS Assistant - Main Menu"
    echo "1. Task Manager"
    echo "2. File Organizer"
    echo "3. System Monitor"
    echo "4. Backup"
    echo "5. Password Manager"
    echo "6. Network Utilities"
    echo "7. Text Manipulation"
    echo "8. Package Management"
    echo "9. Remote Access"
    echo "10. User Management"
    echo "11. System Maintenance"
    echo "12. Software Installation"
    echo "13. Disk Management"
    echo "14. System Information"
    echo "15. Exit"